module Meshing

# Mesh I/O and a partial port of `meshing.py`'s `gs_Domain`. The HDF5 schema
# matches Python exactly so a Julia user can load meshes generated by the
# Python pipeline (and vice versa).
#
# Full triangulation (gs_Domain.build_mesh) requires porting the segment
# merging + Triangle library invocation; that is left as a follow-up.
# `save_gs_mesh` / `load_gs_mesh` are sufficient to drive the ITER and LTX
# tests, which depend on cached meshes (.h5 files) generated once.

using HDF5
using JSON3
using OrderedCollections: OrderedDict

export save_gs_mesh, load_gs_mesh, GsDomain

"""
    save_gs_mesh(pts, tris, regions, coil_dict, cond_dict, filename; use_hdf5=true)

Save a Grad-Shafranov mesh to disk. HDF5 layout matches the one created by
`OpenFUSIONToolkit.TokaMaker.meshing.save_gs_mesh` so files are portable
between the Python and Julia frontends.
"""
function save_gs_mesh(pts::AbstractMatrix, tris::AbstractMatrix,
                      regions::AbstractVector, coil_dict::AbstractDict,
                      cond_dict::AbstractDict, filename::AbstractString;
                      use_hdf5::Bool=true)
    if use_hdf5
        coil_json = JSON3.write(coil_dict)
        cond_json = JSON3.write(cond_dict)
        h5open(filename, "w") do f
            f["mesh/r"] = Matrix{Float64}(pts)
            f["mesh/lc"] = Matrix{Int32}(tris)
            f["mesh/reg"] = Vector{Int32}(regions)
            f["mesh/coil_dict"] = String(coil_json)
            f["mesh/cond_dict"] = String(cond_json)
        end
    else
        d = Dict(
            "mesh" => Dict(
                "r" => collect(eachrow(pts)),
                "lc" => collect(eachrow(tris)),
                "reg" => collect(regions),
                "coil_dict" => coil_dict,
                "cond_dict" => cond_dict,
            )
        )
        open(filename, "w") do io
            JSON3.write(io, d)
        end
    end
    return filename
end

"""
    load_gs_mesh(filename; use_hdf5=true) -> (pts, tris, regions, coil_dict, cond_dict)

Load a mesh saved by either Python or Julia. Returns dictionaries with
ordered keys preserved.
"""
function load_gs_mesh(filename::AbstractString; use_hdf5::Bool=true)
    if use_hdf5
        h5open(filename, "r") do f
            # HDF5.jl preserves on-disk dimension order, which is the inverse
            # of what numpy/h5py wrote. A Python `(np, 2)` array reads back as
            # a Julia `(2, np)` matrix — transpose to keep the user-facing
            # API `[np, 2]` consistent across languages.
            pts_raw = read(f["mesh/r"])
            tris_raw = read(f["mesh/lc"])
            pts = ndims(pts_raw) == 2 && size(pts_raw, 1) == 2 ?
                  Matrix{Float64}(pts_raw') : Matrix{Float64}(pts_raw)
            tris = ndims(tris_raw) == 2 && size(tris_raw, 1) == 3 ?
                   Matrix{Int32}(tris_raw') : Matrix{Int32}(tris_raw)
            regions = Vector{Int32}(read(f["mesh/reg"]))
            coil_str = read(f["mesh/coil_dict"])
            cond_str = read(f["mesh/cond_dict"])
            coil_dict = _json_to_orderdict(coil_str)
            cond_dict = _json_to_orderdict(cond_str)
            return pts, tris, regions, coil_dict, cond_dict
        end
    else
        d = open(filename, "r") do io
            JSON3.read(read(io, String), Dict{String,Any})
        end
        m = d["mesh"]
        pts = Matrix{Float64}(reduce(hcat, m["r"])')
        tris = Matrix{Int32}(reduce(hcat, m["lc"])')
        regions = Vector{Int32}(m["reg"])
        return pts, tris, regions, m["coil_dict"], m["cond_dict"]
    end
end

function _json_to_orderdict(s::AbstractString)
    raw = JSON3.read(s)
    return _to_orderdict(raw)
end
_to_orderdict(x::JSON3.Object) =
    OrderedDict{String,Any}(String(k) => _to_orderdict(v) for (k, v) in pairs(x))
_to_orderdict(x::JSON3.Array) = [_to_orderdict(v) for v in x]
_to_orderdict(x) = x

# ----------------------------------------------------------------------------
# Partial GsDomain. The Python class is ~1200 lines; this is a starter
# scaffold for the most-used entry points. Full triangulation is a TODO.

mutable struct GsDomain
    rextent::Union{Nothing,Float64}
    zextents::Vector{Union{Nothing,Float64}}
    rpad::Float64
    zpad::Vector{Float64}
    regions::OrderedDict{String,Dict{String,Any}}
    contours::OrderedDict{String,Dict{String,Any}}
    coil_dict::OrderedDict{String,Dict{String,Any}}
    cond_dict::OrderedDict{String,Dict{String,Any}}

    function GsDomain(; rextent::Union{Nothing,Real}=nothing,
                        zextents::AbstractVector=Union{Nothing,Float64}[nothing, nothing],
                        rpad::Real=1.2, zpad::AbstractVector=[1.2, 1.2])
        new(rextent === nothing ? nothing : Float64(rextent),
            collect(Union{Nothing,Float64}, zextents),
            Float64(rpad), Vector{Float64}(zpad),
            OrderedDict{String,Dict{String,Any}}(),
            OrderedDict{String,Dict{String,Any}}(),
            OrderedDict{String,Dict{String,Any}}(),
            OrderedDict{String,Dict{String,Any}}(),
        )
    end
end

"""
    define_region!(dom, name, dx, reg_type; eta=nothing, noncontinuous=nothing,
                   nTurns=nothing, coil_set=nothing, allow_xpoints=false,
                   inner_limiter=false)

Define a mesh region. `reg_type` is one of `"plasma"`, `"vacuum"`, `"boundary"`,
`"conductor"`, `"coil"`. See Python `gs_Domain.define_region` for full semantics.
"""
function define_region!(dom::GsDomain, name::AbstractString, dx::Real,
                        reg_type::AbstractString;
                        eta::Union{Nothing,Real}=nothing,
                        noncontinuous::Union{Nothing,Bool}=nothing,
                        nTurns::Union{Nothing,Real}=nothing,
                        coil_set::Union{Nothing,AbstractString}=nothing,
                        allow_xpoints::Bool=false,
                        inner_limiter::Bool=false)
    reg = Dict{String,Any}(
        "type" => reg_type,
        "dx" => Float64(dx),
        "allow_xpoints" => allow_xpoints,
        "inner_limiter" => inner_limiter,
    )
    eta !== nothing && (reg["eta"] = Float64(eta))
    noncontinuous !== nothing && (reg["noncontinuous"] = noncontinuous)
    nTurns !== nothing && (reg["nturns"] = Float64(nTurns))
    coil_set !== nothing && (reg["coil_set"] = String(coil_set))
    dom.regions[String(name)] = reg
    return dom
end

# build_mesh and the Triangle/Cubit pipeline are TODOs. Until then, the
# load_gs_mesh path lets users feed Python-generated meshes directly.

end # module
